# Generated by Django 4.2.2 on 2023-06-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_request_id', models.CharField(max_length=45, null=True)),
                ('asset_request_title', models.CharField(null=True)),
                ('asset_type', models.CharField(max_length=45, null=True)),
                ('asset_type_name', models.CharField(max_length=45, null=True)),
                ('required_date', models.DateField(null=True)),
                ('expected_return_date', models.DateField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('additional_notes', models.CharField(max_length=255)),
                ('delivery_type', models.CharField(choices=[('1', 'Self Pick Up'), ('2', 'Delivery Address')], max_length=45)),
                ('approver_name', models.CharField(max_length=255)),
                ('issued_on', models.DateTimeField(default='00:00:00.000000', null=True)),
                ('reason_for_renewal', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='ReturnAssetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('return_date', models.DateField()),
                ('assets_condition', models.CharField(max_length=255, null=True)),
                ('return_notes', models.CharField(max_length=255, null=True)),
                ('acknowledge_flag', models.BooleanField(max_length=45, null=True)),
                ('asset_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_request', to='assets.assetrequestmodel')),
                ('status', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_type', models.CharField(max_length=45, null=True, unique=True)),
                ('status', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assetrequestmodel',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.status'),
        ),
        migrations.CreateModel(
            name='AssetNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_name', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_name', to='assets.assettypemodel')),
                ('status', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
