# Generated by Django 4.2.2 on 2023-06-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequestmodel',
            name='asset_request_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In_Progress'), ('RETURNED_INITIATED', 'Return_Initiated'), ('WAITING_FOR_APPROVAL', 'Waiting_For_Approval'), ('WAITING_FOR_RENEWAL_APPROVAL', 'Waiting_For_Renewal_Approval')], default='In_Progress', max_length=45),
        ),
        migrations.AlterField(
            model_name='assetrequestmodel',
            name='delivery_type',
            field=models.CharField(choices=[('SELF_PICKUP', 'Self_Pick_Up'), ('DELIVERY_ADDRESS', 'Delivery_Address')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='assetrequestmodel',
            name='issued_on',
            field=models.DateTimeField(null=True),
        ),
    ]
