# Generated by Django 4.2.2 on 2023-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetrequestmodel_asset_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequestmodel',
            name='issued_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
