# Generated by Django 4.2.2 on 2023-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetrequestmodel_issued_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequestmodel',
            name='delivery_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
